# Generated by Django 5.2.8 on 2025-11-13 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Hashtag")),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=80, verbose_name="Hashtag chuẩn hoá"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_hashtags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hashtag nhật ký",
                "verbose_name_plural": "Hashtag nhật ký",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "written_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Thời điểm viết"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký",
                "verbose_name_plural": "Nhật ký",
                "ordering": ["-written_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="entries", to="journal.journalhashtag", verbose_name="Hashtag"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["owner", "written_at"], name="journal_ent_owner_writ_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["owner", "created_at"], name="journal_ent_owner_crea_idx"),
        ),
        migrations.AddIndex(
            model_name="journalhashtag",
            index=models.Index(fields=["owner", "normalized_name"], name="journal_has_owner_n_13017a_idx"),
        ),
        migrations.AddConstraint(
            model_name="journalhashtag",
            constraint=models.UniqueConstraint(
                fields=("owner", "normalized_name"),
                name="journal_hashtag_unique_per_owner",
            ),
        ),
    ]


