# Generated by Django 5.2.8 on 2025-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_content_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_owner_i_0ef972_idx',
            old_name='journal_ent_owner_writ_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_owner_i_abb3df_idx',
            old_name='journal_ent_owner_crea_idx',
        ),
        migrations.RenameIndex(
            model_name='journalhashtag',
            new_name='journal_jou_owner_i_a92288_idx',
            old_name='journal_has_owner_n_13017a_idx',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(verbose_name='Nội dung (HTML)'),
        ),
    ]
