# Generated by Django 5.2.8 on 2025-11-13 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Biệt danh')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Ngành nghề')),
                ('current_address', models.TextField(blank=True, verbose_name='Chỗ ở hiện tại')),
                ('hometown', models.CharField(blank=True, max_length=200, verbose_name='Quê quán')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('importance', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], default='medium', max_length=20, verbose_name='Độ quan trọng')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importance', 'full_name'],
                'indexes': [models.Index(fields=['owner', 'full_name'], name='contacts_co_owner_i_3ce559_idx'), models.Index(fields=['owner', 'importance'], name='contacts_co_owner_i_7a5e97_idx')],
            },
        ),
    ]
