# Generated by Django 5.2.8 on 2025-11-13 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên field')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=20, verbose_name='Loại field')),
                ('target_model', models.CharField(choices=[('contact', 'Contact'), ('wallet', 'Wallet'), ('transaction', 'Transaction')], max_length=50, verbose_name='Model đích')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='Độ dài tối thiểu')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='Độ dài tối đa')),
                ('default_value', models.TextField(blank=True, verbose_name='Giá trị mặc định')),
                ('is_required', models.BooleanField(default=False, verbose_name='Bắt buộc')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='Có thể tìm kiếm')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Có thể lọc')),
                ('options', models.JSONField(blank=True, default=list, help_text='Danh sách các giá trị có thể chọn', verbose_name='Các tùy chọn (cho dropdown/checkbox/radio)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_model', 'order', 'name'],
                'indexes': [models.Index(fields=['target_model', 'is_active'], name='custom_fiel_target__1304b5_idx')],
                'unique_together': {('target_model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True, verbose_name='Giá trị (text)')),
                ('value_number', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Giá trị (số)')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Giá trị (ngày)')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Giá trị (datetime)')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Giá trị (boolean)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfield', verbose_name='Custom Field')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='custom_fiel_content_a0fece_idx'), models.Index(fields=['custom_field', 'content_type', 'object_id'], name='custom_fiel_custom__e51eb4_idx')],
                'unique_together': {('custom_field', 'content_type', 'object_id')},
            },
        ),
    ]
